eval_counselor_checklist:
- api_key_env: OPENAI_API_KEY_SHC
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  column: conversation
  engine: openai-batch
  input_csv: data/singleturn/for_prompting/perfect_score_dialogues_040525_130831.csv
  max_requests: 5
  max_tokens: 500
  model: gpt-4o
  name: convo_traits_simple
  prompt_dir: data/prompts/convo_traits_simple
extract_convo_traits:
- api_key_env: OPENAI_API_KEY_SHC
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  column: conversation
  engine: openai-batch
  input_csv: data/singleturn/for_prompting/perfect_score_dialogues_040525_130831.csv
  max_requests: 5
  max_tokens: 500
  model: gpt-4o
  name: convo_traits_simple
  prompt_dir: data/prompts/convo_traits_simple
dialogue_evals:
# - api_key_env: OPENAI_API_KEY_SHC
#   api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
#   column: conversation
#   engine: openai-batch
#   input_csv: data/singleturn/for_prompting/generated_dialogues_for_eval.csv
#   max_requests: 5
#   max_tokens: 500
#   model: gpt-4o
#   name: patient_eval
#   prompt_dir: data/prompts/patient_eval
# - api_key_env: OPENAI_API_KEY_SHC
#   api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
#   column: conversation_plus_profile
#   engine: openai-batch
#   input_csv: data/singleturn/for_prompting/generated_dialogues_for_eval.csv
#   max_requests: 5
#   max_tokens: 500
#   model: gpt-4o
#   name: patient_unit_tests
#   prompt_dir: data/prompts/patient_unit_tests
- api_key_env: OPENAI_API_KEY_SHC
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  column: conversation
  engine: openai-batch
  input_csv: data/singleturn/for_prompting/generated_dialogues_for_eval.csv
  max_requests: 5
  max_tokens: 500
  model: gpt-4o
  name: dynamic_counselor_rubric
  prompt_dir: data/prompts/counselor_eval_short
- api_key_env: OPENAI_API_KEY_SHC
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  column: conversation
  engine: openai-batch
  input_csv: data/singleturn/for_prompting/generated_dialogues_for_eval.csv
  max_requests: 5
  max_tokens: 500
  model: gpt-4o
  name: counselor_unit_tests
  prompt_dir: data/prompts/counselor_unit_tests_short
dialogue_generation_20250509_114018:
- api_key_env: OPENAI_API_KEY_VICKY
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  column: convo_history
  engine: openai-batch
  generation_params: config/generation_params.json
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_1.csv
  max_requests: 4
  max_tokens: 500
  model: gpt-4o
  name: dialogue_turn_1_patient
  prompt_dir: data/prompts/dialogue_generation/patient_turn_1
static_evals_comparison:
- api_key_env: OPENAI_API_KEY_SHC
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  column: comparison_input
  engine: openai-batch
  input_csv: data/singleturn/for_prompting/static_eval_comparison.csv
  max_requests: 4
  max_tokens: 1000
  model: gpt-4o
  name: static_evals_rubric
  prompt_dir: data/prompts/counselor_comparison
- api_key_env: OPENAI_API_KEY_SHC
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  column: comparison_input
  engine: openai-batch
  input_csv: data/singleturn/for_prompting/static_eval_comparison.csv
  max_requests: 4
  max_tokens: 500
  model: gpt-4o
  name: static_evals_comparison_unit_tests
  prompt_dir: data/prompts/counselor_unit_tests_message_level
static_evals_generation:
- api_key_env: OPENAI_API_KEY
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/o1-mini/chat/completions?api-version=2024-10-21
  column: convo_history
  engine: openai-batch
  generation_params: config/generation_params.json
  input_csv: data/singleturn/for_prompting/static_eval_input.csv
  max_requests: 4
  max_tokens: 2000
  model: o1-mini
  name: static_evals_generation
  prompt_dir: data/prompts/base_prompt
- api_key_env: CLAUDE_API_KEY
  api_url: https://apim.stanfordhealthcare.org/awssig4claude37/aswsig4claude37
  column: convo_history
  engine: openai-batch
  generation_params: config/generation_params.json
  input_csv: data/singleturn/for_prompting/static_eval_input.csv
  max_requests: 4
  max_tokens: 200
  model: claude-3-7-sonnet-20250219-v1
  name: static_evals_generation_claude
  prompt_dir: data/prompts/base_prompt
- api_key_env: GEMINI_API_KEY
  api_url: https://apim.stanfordhealthcare.org/gcp-gem20flash-fa/apim-gcp-gem20flash-fa
  column: convo_history
  engine: openai-batch
  generation_params: config/generation_params.json
  input_csv: data/singleturn/for_prompting/static_eval_input.csv
  max_requests: 4
  max_tokens: 200
  model: gemini-2.0-flash
  name: static_evals_generation_gemini
  prompt_dir: data/prompts/base_prompt
- api_key_env: GEMINI_API_KEY
  api_url: https://apim.stanfordhealthcare.org/gcpgemini/apim-gcp-oauth-fa
  column: convo_history
  engine: openai-batch
  generation_params: config/generation_params.json
  input_csv: data/singleturn/for_prompting/static_eval_input.csv
  max_requests: 4
  max_tokens: 200
  model: gemini-1.5-pro
  name: static_evals_generation_gemini_1_5_pro
  prompt_dir: data/prompts/base_prompt
- api_key_env: LLAMA_API_KEY
  api_url: https://apim.stanfordhealthcare.org/llama3370b/v1/chat/completions
  column: convo_history
  engine: openai-batch
  generation_params: config/generation_params.json
  input_csv: data/singleturn/for_prompting/static_eval_input.csv
  max_requests: 4
  max_tokens: 200
  model: Llama-3.3-70B-Instruct
  name: static_evals_generation_llama
  prompt_dir: data/prompts/base_prompt
dialogue_generation_20250509_135529:
- name: dialogue_turn_1_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_1.csv
  prompt_dir: data/prompts/dialogue_generation/patient_turn_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
dialogue_generation_20250509_140239:
- name: dialogue_turn_1_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_1.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
dialogue_generation_20250509_141426:
- name: dialogue_turn_1_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_1.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
dialogue_generation_20250509_141626:
- name: dialogue_turn_1_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_1.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_2_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_2.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: claude-3-7-sonnet-20250219-v1
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/awssig4claude37/aswsig4claude37
  api_key_env: CLAUDE_API_KEY
  generation_params: config/generation_params.json
- name: dialogue_turn_3_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_3.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_4_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_4.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: claude-3-7-sonnet-20250219-v1
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/awssig4claude37/aswsig4claude37
  api_key_env: CLAUDE_API_KEY
  generation_params: config/generation_params.json
- name: dialogue_turn_5_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_5.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_6_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_6.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: claude-3-7-sonnet-20250219-v1
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/awssig4claude37/aswsig4claude37
  api_key_env: CLAUDE_API_KEY
  generation_params: config/generation_params.json
- name: dialogue_turn_7_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_7.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_8_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_8.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: claude-3-7-sonnet-20250219-v1
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/awssig4claude37/aswsig4claude37
  api_key_env: CLAUDE_API_KEY
  generation_params: config/generation_params.json
- name: dialogue_turn_9_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_9.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_10_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_10.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: claude-3-7-sonnet-20250219-v1
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/awssig4claude37/aswsig4claude37
  api_key_env: CLAUDE_API_KEY
  generation_params: config/generation_params.json
- name: dialogue_turn_11_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_11.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
dialogue_generation_20250509_143015:
- name: dialogue_turn_1_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_1.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_2_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_2.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  api_key_env: OPENAI_API_KEY_SHC
  generation_params: config/generation_params.json
- name: dialogue_turn_3_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_3.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_4_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_4.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  api_key_env: OPENAI_API_KEY_SHC
  generation_params: config/generation_params.json
- name: dialogue_turn_5_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_5.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_6_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_6.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  api_key_env: OPENAI_API_KEY_SHC
  generation_params: config/generation_params.json
- name: dialogue_turn_7_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_7.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_8_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_8.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  api_key_env: OPENAI_API_KEY_SHC
  generation_params: config/generation_params.json
- name: dialogue_turn_9_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_9.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
- name: dialogue_turn_10_counselor
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_10.csv
  prompt_dir: data/prompts/dialogue_generation/base_instructions3
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://shcopenaisandbox.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
  api_key_env: OPENAI_API_KEY_SHC
  generation_params: config/generation_params.json
- name: dialogue_turn_11_patient
  input_csv: data/singleturn/for_prompting/dialogue_prompts_turn_11.csv
  prompt_dir: data/prompts/dialogue_generation/anxiety_1
  column: convo_history
  model: gpt-4o
  engine: openai-batch
  max_requests: 4
  max_tokens: 500
  api_url: https://apim.stanfordhealthcare.org/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
  api_key_env: OPENAI_API_KEY_VICKY
  generation_params: config/generation_params.json
categorize_edits:
- name: categorize_edits
  api_key_env: OPENAI_API_KEY
  api_url: "https://api.openai.com/v1/chat/completions"
  column: merged_text
  engine: openai-batch
  input_csv: /home/stanford/vf_copilot/edit_analysis/message_datasets/cleaned_hashed_dataset.csv
  max_requests: 4
  max_tokens: 500
  model: gpt-4.1
  prompt_dir: data/prompts/categorize_edits